stages:
- maven
- docker

cache:
  untracked: true
  key: "ldap-m2"
  paths:
  - m2 

build-jar:
  stage: maven
  image: harbor.cloudpowered.services/mcon-group-public/centos8-base:latest
  tags: 
  - docker
  script:
  - sh scripts/build-maven.sh
  only:
  - master
  artifacts:
    paths:
    - shrtnr-app/target/shrtnr-app.jar
    expire_in: 20 mins
    
build-docker:
  stage: docker
  image: harbor.cloudpowered.services/mcon-group-public/centos8-base:latest
  tags: 
  - docker
  script:
  - sh scripts/build-docker.sh
  only:
  - master
