server.servlet.contextPath: /
spring.http.encoding.charset: UTF-8
spring.http.encoding.enabled: true
spring.http.encoding.force: true
spring.resources.cache.period: 1

spring.datasource.platform: h2
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.url: jdbc:h2:file:${datadir}/shrtnr;MODE=MYSQL

flyway.enabled: true

spring.mvc.locale: de_DE

logging.level.org.springframework.web: DEBUG
host: "http://127.0.0.1:8080/"
include: |
   <div class="alert alert-danger">
      this include can be anything you want
   </div> 